enc: h264: ffmpeg: Use avfilter_graph_alloc_filter
... instead of avfilter_graph_create_filter.

This fixes the following problem introduced by ffmpeg 8:

ERROR: libav: 0: Setting BufferSourceContext.pix_fmt to a HW format requires hw_frames_ctx to be non-NULL!
DEBUG: ../neatvnc/src/server.c: 136: H.264 encoding is unavailable